# Travis CI build file for Kitura-MustacheTemplateEngine.
# Kitura runs on OS X and Linux (Ubuntu v14.04).

# whitelist (branches that should be built)
branches:
  only:
    - master
    - develop

matrix:
  include:
    - os: linux
      dist: xenial 
      sudo: true
      env: SWIFT_SNAPSHOT=4.1

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
  - ulimit -n 10000
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
